modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "hads_switch"
version = "${file.jarVersion}"
displayName = "HADS Switch"
description = '''Adds a block to toggle TARDIS HADS (Hostile Action Displacement System), plus a fix for the missing Renaissance police box sign.'''

[[dependencies.hads_switch]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.hads_switch]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.hads_switch]]
    modId = "aitforger"
    mandatory = true
    versionRange = "[1.0.4,)"
    ordering = "AFTER"
    side = "BOTH"
